// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SouthWind.Data;

#nullable disable

namespace SouthWind.Data.Migrations
{
    [DbContext(typeof(SouthWindDbContext))]
    [Migration("20230522065217_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SouthWind.Data.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kitap"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Müzik DVD"
                        });
                });

            modelBuilder.Entity("SouthWind.Data.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2023, 5, 21, 6, 52, 17, 133, DateTimeKind.Local).AddTicks(1791),
                            ProductId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2023, 5, 20, 6, 52, 17, 133, DateTimeKind.Local).AddTicks(1960),
                            ProductId = 1,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2023, 5, 17, 6, 52, 17, 133, DateTimeKind.Local).AddTicks(1963),
                            ProductId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 6,
                            OrderDate = new DateTime(2023, 5, 12, 6, 52, 17, 133, DateTimeKind.Local).AddTicks(1987),
                            ProductId = 2,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 7,
                            OrderDate = new DateTime(2023, 5, 2, 6, 52, 17, 133, DateTimeKind.Local).AddTicks(1989),
                            ProductId = 2,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 8,
                            OrderDate = new DateTime(2023, 3, 23, 6, 52, 17, 133, DateTimeKind.Local).AddTicks(1991),
                            ProductId = 2,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("SouthWind.Data.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            InStock = true,
                            ListPrice = 12500.50m,
                            Name = "Sani Dual Monitor 1240"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            InStock = true,
                            ListPrice = 11000.50m,
                            Name = "ElGi Ultra HD Monitor"
                        });
                });

            modelBuilder.Entity("SouthWind.Data.Entity.Order", b =>
                {
                    b.HasOne("SouthWind.Data.Entity.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SouthWind.Data.Entity.Product", b =>
                {
                    b.HasOne("SouthWind.Data.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SouthWind.Data.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SouthWind.Data.Entity.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
